export const USER_MESSAGE = 'USER_MESSAGE';
export const SERVER_MESSAGE = 'SERVER_MESSAGE';
export const SERVER_UPDATE_MESSAGES = 'SERVER_UPDATE_MESSAGES';
export const SERVER_UPDATE_USERS = 'SERVER_UPDATE_USERS';